---
meta:
  name:    postgres
  release: PostgreSQL
  target:  sw
  url:     https://ci.vsphere.starkandwayne.com

  initial_version: 1.0.0

  bosh-lite:
    target: https://10.58.111.44:25555
    deployment: postgres-warden

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   postgres-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/postgres-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/postgres-boshrelease/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/postgres-boshrelease/slack:webhook" ))
    channel: '#botspam'
